weniv/MAKE-RE_ver2

src/components/templates/Intro/IntroPreview.jsx, src/pages/PreviewPage.jsx
=> 💄 Style: 자기소개서 미리보기 UI

src/components/templates/Profile/ProfilePreview.jsx
프로필 메인컬러 컨텍스트 적용 (프로필만 예외적으로  `PreviewSubtitle` 컴포넌트를 사용하지 않아 생기는 이슈)
close #110
=> 💄 Style: 프로필 메인컬러 컨텍스트 적용 

src/components/templates/Certificate/CertificatePreview.jsx, src/components/templates/Education/EducationPreview.jsx, src/components/templates/Intro/IntroPreview.jsx
날짜, 타이틀이 모두 없는 경우 미리보기 페이지에서 해당 섹션 전체 제외
close #112
=> ✨ Feat: 컨텐츠가 없는 경우 미리보기 제외

src/components/templates/Education/EducationPreview.jsx, src/components/templates/Experience/ExperiencePreview.jsx, src/pages/PreviewPage.jsx
미리보기 페이지 내 경험 컴포넌트 추가
close #105
=> 💄 Style: 미리보기 내 경험 컴포넌트 추가

src/components/organisms/Header/Header.jsx, src/pages/PreviewPage.jsx
=> 💄 Style: 헤더와 메인 너비 통일

src/components/atoms/Input/DefaultTextarea.jsx, src/components/atoms/PreviewItem/PreviewMonthItem.jsx, src/components/organisms/Component/Career.jsx, src/components/organisms/Component/index.js, src/components/templates/Career/Career.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Career/index.js, src/components/templates/Url/UrlPreview.jsx, src/pages/PreviewPage.jsx, src/pages/WritePage.jsx
Summary
- 출력 페이지 Career 컴포넌트를 구현했습니다.
Check
=> 📝PR: 출력 페이지 Career 컴포넌트 구현

src/components/atoms/Input/DefaultTextarea.jsx
자기소개서 입력창 line-height 적용
close #127
=> :lipstick: Fix: intro line-height 적용

src/components/atoms/PreviewItem/PreviewLink.jsx, src/components/atoms/PreviewItem/PreviewMonthItem.jsx, src/components/organisms/Component/index.js, src/components/templates/Project/Project.jsx, src/components/templates/Project/ProjectPreview.jsx, src/components/templates/Project/index.js, src/pages/PreviewPage.jsx, src/pages/WritePage.jsx
Summary
출력 페이지 Project 컴포넌트를 구현했습니다.
Check
=> 📝PR: 출력 페이지 Project 컴포넌트 구현

src/components/templates/Career/Career.jsx, src/components/templates/Certificate/Certificate.jsx, src/components/templates/Education/Education.jsx, src/components/templates/Experience/Experience.jsx, src/components/templates/Intro/Intro.jsx, src/components/templates/Profile/Profile.jsx, src/components/templates/Project/Project.jsx, src/components/templates/Url/Url.jsx
=> 📝 Edit: 작성페이지 섹션별 설명 문구 수정

src/pages/PreviewPage.jsx
출력페이지에도 footer컴포넌트 보이도록 변경
close: #133
=> :lipstick: Add: preivew page footer 추가

src/components/templates/Profile/Profile.jsx, src/utils/updateProfile.jsx
전화번호 인풋 창 텍스트 입력 제한
프로필 컴포넌트 내 전화번호 입력 인풋창에서 0-9숫자 외 입력할 시 빈 문자열로 대체
close #123
=> :bug: Fix: 전화번호 인풋 텍스트 입력제한

src/components/organisms/Nav/PreviewBox.jsx, src/context/RemoteContext.jsx
입력페이지에서 미리보기 버튼 클릭 시 데이터 저장 후 미리보기 페이지로 이동
close: #126
=> :sparkles: Feat: 미리보기 버튼 클릭시 데이터 저장 기능 추가

src/components/templates/Profile/ProfilePreview.jsx
단일 요소일 경우 값이 없다면 => 요소 제거
미리보기 페이지의 프로필 섹션에서 값이 없는 요소가 없다면 렌더링 되지 않도록 변경
close: #144
=> :lipstick: Fix: 입력 상황에 따른 조건부 렌더링

src/components/atoms/ColorIcon/ColorIcon.jsx
=> :lipstick: Edit: 배포 페이지 아이콘 색상 오류 수정

src/components/atoms/Input/DefaultTextarea.jsx, src/components/organisms/Component/Career.jsx, src/components/templates/Career/Career.jsx, src/utils/updateData.jsx
- 이전 코드에서 최초 입력시 height가 최소 높이보다 작아지는 문제 해결
=> 🐛 Fix: Career 컴포넌트 Textarea의 height가 가변적으로 설정되도록 수정

src/App.jsx, src/components/atoms/Button/MainBtn.jsx, src/components/atoms/Button/ToggleBtn.jsx, src/components/atoms/ColorIcon/ColorIcon.jsx, src/components/atoms/Nav/NavList.jsx, src/components/organisms/Header/Header.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/components/templates/Profile/Profile.jsx
사용자 지정 색 적용 대상을 `mainColor` 적용 받는 전체 컴포넌트에서 pdf 출력 범위로만 한정 
close #156
=> 💄 Style: colorPicker 값 적용 대상 수정

src/components/atoms/Button/MainBtn.jsx, src/components/atoms/Button/SaveBtn.jsx, src/components/atoms/Input/DefaultInput.jsx, src/components/organisms/Component/Career.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/context/ResumeContext.jsx
- Career 작성페이지에서 "회사명"을 필수항목으로 처리함
- 임시저장, 미리보기 버튼 클릭시 필수항목이 입력되지않은 경우 해당 항목을 입력하라는 문구가 출됨
=> ✨ Feat: Career 작성페이지 필수 항목 예외처리 #161

src/components/organisms/Component/Career.jsx, src/components/organisms/Component/Project.jsx
- Project 작성페이지에서 "프로젝트명"을 필수항목으로 처리함
- 임시저장, 미리보기 버튼 클릭시 필수항목이 입력되지않은 경우 해당 항목을 입력하라는 문구가 출력됨
=> ✨ Feat: Project 필수 항목 예외처리 #162

src/App.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/context/Providers.jsx, src/pages/WritePage.jsx, src/utils/dnd.jsx, src/utils/saveData.js
- 필수값 검증 기능을 추가하며 미리보기 버튼 클릭시 해당 페이지로 이동하지않는 버그 발생하여 수정
- 추후 서버와의 통신시 코드 가독성을 위해 ResumeData를 저장하는 부분을 saveData 함수로 분리
- App.jsx에 Provider의 중첩해소를 위해 Providers.jsx 파일을 생성하여 분리
=> ♻️ Refactor: 미리보기 페이지 이동 관련 버그 해결 및 코드 정리

src/components/atoms/Nav/NavList.jsx
(10.25 회의 결과 내용 반영) 체크 아이콘의 기획 의도가 애매하여 UI 제거
close #165
=> 💄 Style: nav 체크 아이콘 제거

src/components/atoms/Button/ToggleBtn.jsx
(경림님 피드백) 위니브 월드 버튼 사이즈에 맞춰 토글 버튼 디자인 통일 
close #172
=> 💄 Style: ToggleBtn 사이즈 변경

src/components/atoms/Title/WriteSubtitle.jsx, src/components/atoms/Title/WriteTitle.jsx
(경림님 피드백) 디자인에 맞춰 타이틀 `font-weight` 일괄 수정
close #174
=> 💄 Style: 타이틀 font-weight 변경

src/pages/PreviewPage.jsx, src/pages/WritePage.jsx
- (경림님 피드백) 컨텐츠 최소 높이 지정: `100vh`
close #178
=> 💄 Style: 컨텐츠 최소 높이 설정을 통한 footer 위치 고정

src/components/atoms/Input/DefaultTextarea.jsx, src/styles/GlobalStyles.jsx
위니브 스크롤 디자인에 맞춰 `textarea` 스크롤 디자인 수정 및 `GlobalStyles` 추가 
close #183
=> 💄 Style: textarea 커스텀 스크롤 수정

src/components/atoms/Input/DefaultInput.jsx, src/components/organisms/Component/Career.jsx, src/components/organisms/ComponentHeader/ComponentHeader.jsx, src/components/templates/Career/Career.jsx, src/components/templates/Career/CareerPreview.jsx, src/data/dummy.js
- form이 닫힌 경우에는 필수 입력 요소가 감지되지않는 문제가 있었음
- form이 열린 경우에는 require 요소가 해당 input을 감지
- form이 닫혀있고, 필수 입력 요소가 입력 되지 않은 경우에는 데이터를 서버에 저장하지않음
- 필수 입력 요소가 입력 되지 않은 경우에는 미리 보기 페이지로 이동 후 다시 작성 페이지로 돌아왔을때 해당 요소가 사라짐
- 최초에 생성되어있는 빈 form 1개는 필수 입력 요소를 입력하지않아도 작성페이지에는 존재하나, 미리보기 페이지에는 출력되지않음
=> 📝 PR: career 필수 입력 요소 수정 #185

src/components/organisms/Component/Career.jsx, src/components/organisms/Component/Project.jsx, src/components/templates/Career/Career.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Project/Project.jsx, src/components/templates/Project/ProjectPreview.jsx
- caeer 컴포넌트와 동일
- career, project 미리보기 출력 변경
- form이 열린 경우에는 require 요소가 해당 input을 감지
- form이 닫혀있고, 필수 입력 요소가 입력 되지 않은 경우에는 데이터를 서버에 저장하지않음
- 필수 입력 요소가 입력 되지 않은 경우에는 미리 보기 페이지로 이동 후 다시 작성 페이지로 돌아왔을때 해당 요소가 사라짐
- 최초에 생성되어있는 빈 form 1개는 필수 입력 요소를 입력하지않아도 작성페이지에는 존재하나, 미리보기 페이지에는 출력되지않음
=> 📝 PR: project필수 입력 요소 수정 #187

src/components/atoms/Nav/NavList.jsx, src/components/organisms/Nav/NavBar.jsx
- 프로필 항목을 드래그앤 드롭 할 수 없도록 해당 항목에서 dnd 버튼을 숨김
=> 📝 PR: DND 프로필 항목 제외 #163

src/components/atoms/Button/ToggleBtn.jsx, src/components/organisms/Header/Header.jsx, src/pages/PreviewPage.jsx, src/pages/WritePage.jsx
디자인이 추가됨에 따라 Header 내 다음과 같은 옵션을 추가했습니다.
- `hasCreate`: '이력서 만들기' 버튼 유무
- `hasProfile` '프로필' 버튼 유무
- `isCenter`: 중앙 정렬 유무 (버튼 없이 로고만)
- `isWhite`: 흰 배경 유무 (배경색 추가: `background-color`, `gray-lv1-color`)
- 프로필 버튼 클릭 시 나타나는 메뉴 리스트에 대한 라우팅은 해당 PR에서 구현되지 않았습니다.
- 사용 시 다음과 같이 옵션을 지정해주세요.
```js
<Header
options={{
isCenter: false,
hasProfile: true,
hasCreate: true,
isWhite: false,
}}
/>
```
디자인은 [피그마 링크](https://www.figma.com/file/9eOCbOchfgELOxeR20BY4b/%EB%A9%94%EC%9D%B4%EC%BB%A4%EB%A6%AC(%EC%9D%B4%EB%A0%A5%EC%84%9C-%EC%84%9C%EB%B9%84%EC%8A%A4)?type=design&node-id=1366%3A3057&mode=design&t=AZb1JeI1D8l5q1Jk-1)를 참고해주세요.
close #190
=> 💄 Style: Header 옵션 추가 

src/App.jsx, src/pages/LandingPage.jsx, src/pages/NotFoundPage.jsx, src/pages/index.js, src/styles/GlobalStyles.jsx
=> 📝 PR: 랜딩페이지 구현

src/components/organisms/Component/DeleteModal.jsx, src/components/organisms/Component/Resume.jsx, src/components/organisms/Header/Header-style.jsx, src/components/organisms/Header/Header.jsx
- 이력서 삭제 모달: Resume -> DeleteModal.jsx로 분리
- 헤더 스타일: Header-style.jsx로 분리
- 현재 디자인 상 삭제 외 모달이 필요 없어 DeleteModal만 구현, 추후 필요 시 수정 필요
=> 🚚 Move: 삭제 모달 및 헤더 스타일 코드 분리

src/components/organisms/Nav/MyPageNav.jsx
=> 💄 Style: 마이페이지 nav 최소 너비 지정

src/components/atoms/Auth/Layout.jsx, src/pages/SignupPage.jsx
- 회원가입 페이지 내 이용약관 및 개인정보처리방침 링크 연결
- 회원가입, 로그인 페이지 헤더 추가 (Auth > `Layout.jsx`)
=> 📝 PR: Auth 페이지 링크 연결 및 Header 추가

src/components/organisms/Nav/NavBar.jsx, src/components/templates/Aside/Aside.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Certificate/CertificatePreview.jsx, src/components/templates/Education/EducationPreview.jsx, src/components/templates/Experience/ExperiencePreview.jsx, src/components/templates/Intro/IntroPreview.jsx, src/components/templates/Project/ProjectPreview.jsx, src/components/templates/Url/UrlPreview.jsx, src/pages/PreviewPage.jsx, src/utils/getSectionId.jsx
이전 pr close하고 기능별로 분리해서 merge 중
=> 📝 PR: navBar 항목 클릭시 해당 섹션으로 스크롤 이동

src/components/organisms/Component/DeleteModal.jsx, src/components/organisms/Component/Resume.jsx, src/pages/myResume.jsx
아래 기능 관련 기본 로직 작성 (추후 API 통신 로직 추가 및 endpoint 설정 필요)
- 이력서 삭제
- 이력서 추가
- 이력서 이름 수정
- 이력서 불러오기
=> ✨ Feat: 이력서 관리 페이지 관련 로직 뼈대 작업

src/components/organisms/Explain/ExpalinBox.jsx, src/components/organisms/Explain/Explain.jsx
=> :lipstick: Edit: 오버레이 설명 반응형 처리

src/components/organisms/Component/Experience.jsx, src/components/templates/Experience/Experience.jsx
- 경험 섹션 항목 추가
- 경험 데이터 수정
- experience 구조
```py
{
id: nextId.current,
title: '',
startDate: '',
endDate: '',
inProgress: false,
content: '',
link: '',
}
```
=> 📝 PR: 경험 섹션 항목 추가

src/components/atoms/Input/DateInput.jsx, src/components/organisms/Component/Certificate.jsx, src/components/organisms/Component/Education.jsx
- 자격증: 발급 기관, 점수 필드 추가
- 교육: 설명 필드 추가
close #222
=> ✨ Feat: 교육 및 자격증 섹션 필드 추가

src/components/atoms/Auth/AuthCode.jsx, src/components/atoms/Auth/Input.jsx, src/components/atoms/Auth/Label.jsx, src/components/atoms/Auth/Layout.jsx, src/components/atoms/Auth/WarningMsg.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx, src/styles/GlobalStyles.jsx
- 로그인 페이지 다크모드 적용
- 회원가입 페이지 다크모드 적용
=> 📝 PR: 로그인/회원가입 페이지 다크모드 적용

src/api/GithubApi.jsx, src/components/templates/Profile/Profile.jsx, src/components/templates/Profile/ProfilePreview.jsx
- 깃허브 이미지 불러온 후 이미지 제거 기능 추가
- 데이터 빈 값일 때 미리보기 페이지 얘외처리
- mainColor변경시 컬러팔레트 외 지정되어있는 5가지 색상으로 선택하면, 색상코드가 아닌 전역 변수명으로 mainColor가 변경이 됩니다. 이 부분 수정해서 따로 pr 올리겠습니다.
close: #153 , #145
=> :bug: Fix: 깃허브 데이터 빈값 예외처리

src/api/GithubApi.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Profile/ProfilePreview.jsx, src/pages/PreviewPage.jsx
- 커밋이미지 로드 실패시 이미지 제거 및 "*유효하지 않은 아이디입니다." 경고 문구 추가
- 미리보기 페이지에서 mainColor가 variable변수일 경우에 따른 커밋이미지 mainColor 적용
=> 🐛 Add: 커밋이미지 로드 상태에 따른 깃허브 아이디 검증

src/components/atoms/DropBox/DropBox.jsx, src/components/templates/Profile/Profile.jsx
🐛 Edit: 이메일 주소 수정시 "직접 입력" 변경
이메일 주소 선택 후 수정시 선택된 이메일 주소 유지 => "직접 입력"으로 변경
close: #125
=> 🐛 Edit: 이메일 주소 수정시 "직접 입력" 변경

src/components/templates/Intro/Intro.jsx
=> :lipstick: Edit: Intro textarea line-height 변경

src/assets/loader.svg, src/components/templates/Profile/ProfilePreview.jsx
=> :bento: Update: 로딩 이미지 변경

src/App.jsx, src/components/organisms/Component/Resume.jsx, src/components/organisms/Header/Header.jsx, src/components/organisms/Nav/MyPageNav.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/pages/LandingPage.jsx, src/pages/LoginPage.jsx, src/pages/NotFoundPage.jsx, src/pages/QuitPage.jsx, src/pages/SignupDonePage.jsx, src/pages/SignupPage.jsx
- 기존 라우터 처리 방식: `/MAKE-RE_ver/` 로 시작 -> 커스텀 도메인 연결 시 리드미 파일만 표시되는 현상 발생
- 수정 내용: 모든 라우터에 `/MAKE-RE_ver/` 제외
=> 🐛 Fix: 라우터 경로 수정

src/utils/updateData.jsx
- 한글 입력 시 maxLength를 넘어서 입력되는 문제 처리
- maxLength 값이 없으면 e.target.maxLength의 값은 -1
- 값에 따라서 슬라이싱 처리를 분기
- maxLength가 없는 경우 슬라이싱 처리 없이 데이터 업데이트
```js
setData(
data.map((el, i) =>
i === idx
? {
...el,
[name]:
e.target.maxLength === -1
? value
: value.slice(0, e.target.maxLength),
}
: el
)
)
```
=> :memo: PR: 한글 입력에 대한 maxLength 슬라이싱 처리

.github/workflows/deploy.yml
- custom domain이 사라지는 오류 처리를 위해 배포 파일 수정
=> :memo: Edit: 배포 파일 cname 추가

src/components/atoms/Input/DefaultTextarea.jsx, src/components/organisms/Component/Career.jsx, src/components/templates/Career/Career.jsx
- DefaultTextarea 컴포넌트가 사용자의 입력에 따라 높이가 자동으로 변경되도록 처리한 부분에서 문제 발생.
발생한 문제
- 아래 그림과 같이 작성했던 글을 지워도 높이가 줄어들지않음
- 간헐적으로 높이가 최소 지정 높이보다 작아지는 현상 발생
- 새로고침시 확장된 크기가 축소되어 글자가 잘리는 문제
- DefaultTextarea에 handleResizeHeight 함수를 추가하여 높이가 가변적으로 변경될 수 있도록 수정
=> 🐛 Bug: DefaultTextarea 컴포넌트 height 자동변경 변경 버그 #267

public/index.html
=> :mag: Add: 네이버 서치어드바이저 메타 태그 추가

package-lock.json, package.json, src/index.js, src/utils/metaData.jsx
react-snap을 이용한 페이지별 html 파일 생성으로 SEO 개선 작업
close:  #258
=> 📦 Add: react-snap

package.json
=> :package: Add: 최적화 설정 추가

package.json
=> :package: Add: build 테스트

src/index.js, src/utils/metaData.jsx
index.js 파일 내 react snap 설정 변경
=> :mag: Edit: react snap 설정 변경

public/index.html
csr로 메타데이터 적용 안되는 이슈 해결전 까지 index.html에 직접 메타데이터 추가
=> :mag: Add: index.html 파일 내 임시 메타 태그 추가

public/index.html
=> :mag: Edit: 제너레이터 사용한 메타데이터 변경

src/components/templates/Profile/DefaultProfile.jsx, src/components/templates/Profile/Profile.jsx, src/pages/MyProfilePage.jsx
- 마이페이지에서 설정한 기본 프로필이 새로 생성된 이력서의 프로필 파트 초깃값으로 사용되도록 수정
- 새 이력서를 생성하면 마이페이지의 기본 프로필이 초깃값으로 적용됩니다.
- 이력서 내부에서 프로필을 변경시, 변경된 정보는 해당 프로필에만 적용됩니다.
=> 📝 PR: 기본 프로필 설정 및 불러오기

src/pages/myResumePage.jsx
=> 📝 PR: 새로운 이력서 생성시 id 값이 null로 삽입되는 문제 해결 #297

package-lock.json, package.json, src/components/templates/Profile/DefaultProfile.jsx
=> ✨ Feat: 기본 프로필 페이지 초기화 시 로컬 스토리지 데이터 가져오기

src/components/atoms/Input/DefaultInput.jsx, src/components/atoms/Input/RequireInput.jsx, src/components/atoms/PreviewItem/PreviewLink.jsx, src/components/organisms/Component/Career.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Profile/Profile-style.jsx, src/components/templates/Profile/Profile.jsx, src/components/templates/Profile/ProfilePreview.jsx, src/components/templates/Project/ProjectPreview.jsx, src/utils/updateData.jsx
- 🐛 Bug: 미리보기 페이지 잔디 이미지 메인 컬러 반영 안 되는 이슈 #306
- 🐛 Bug: 미리보기 프로필 블로그 링크 다크모드 반영 안되는 이슈 #307
- 🐛 Bug: 미리보기 페이지에서 커리어, 프로젝트 내용이 없는 경우에도 제목이 출력되는 이슈 #308
- 🐛 Bug: 작성페이지 프로필, 커리어, 프로젝트의 필수 항목이 입력되지 않을 시 화면에 경고 메시지가 출력 되지 않는 이슈 #309
=> 📝 PR: QA 체크 후 수정사항 반영

src/components/atoms/PreviewItem/PreviewMonthItem.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Project/ProjectPreview.jsx
- 날짜 컴포넌트 등 다크모드 변수가 적용되지 않은 부분이 있어 수정하였습니다.
=> 💄 Style: 미리보기 테마 변수 미적용 파트 수정

src/components/organisms/Header/Header.jsx, src/pages/MyProfilePage.jsx
- 프로필 페이지 header 내 다크모드 토글 제외 모든 버튼 제거
- 작성 페이지 header 내 프로필 버튼 라우팅 수정 (이력서 관리 → 프로필 페이지)
- 이동 페이지 고려해 `Header.jsx` 내 함수명 변경 
- moveWrite → moveMyResume
- moveMypage → moveMyProfile
close #316
=> ✨ Feat: Header 기능 중복 아이콘 삭제 및 라우팅 변경

src/components/templates/Career/CareerPreview.jsx
=> 💄UI: 커리어 담당 업무 미리보기 시 줄바꿈 유지
