weniv/MAKE-RE_ver2

src/components/organisms/ColorPicker/ColorPicker.jsx
ColorPicker 테마 변경
- 테마 변경 (Sketch -> Block)
- 화살표 스타일 커스텀
close #33
=> ✨ Feat: ColorPicker 테마 변경

src/components/atoms/ColorIcon/ColorIcon.jsx, src/components/atoms/PreviewItem/PreviewLink.jsx, src/components/templates/Url/Url.jsx, src/components/templates/Url/UrlPreview.jsx, src/pages/PreviewPage.jsx
- 출력 페이지 URL컴포넌트를 구현했습니다.
- 미리보기 링크 박스(PreviewLink), 색상아이콘(ColorIcon) 컴포넌트 구현
1. PreviewLink
- 링크 주소를 **절대 경로**로 변경합니다. (ex. www.paullab.co.kr -> http://www.paullab.co.kr)
- 링크 클릭 시 새창에서 열립니다. `target="_blank"`
2. ColorIcon
- 메인 색상에 따라 색상이 변경되는 아이콘 컴포넌트입니다.
- 컴포넌트를 사용하는 곳에서 아이콘 이미지를 import 한 후, props.iconPath로 전달합니다.
```js
import iconPath from '../assets/icon/...'
<ColorIcon iconPath={iconPath} />
```
=> 📝 PR: 출력 페이지 URL 컴포넌트 구현

src/components/organisms/Nav/NavBar.jsx, src/components/templates/Profile/Profile.jsx, src/context/ResumeContext.jsx, src/pages/PreviewPage.jsx, src/utils/dnd.jsx
1. 작성 페이지에서 드래그앤 드롭을 통해 navList 리스트 순서를 변경하고, 그 순서에 따라 미리보기  페이지에서 컴포넌트를 동적으로 출력하는 기능 추가
2. 작성 페이지에서 변경한 navList 순서가 미리보기 페이지에서도 유지되도록 수정
3. 변경된 navList 순서가 새로고침 이전까지 유지되도록 수정
- `ResumeContext`에서 `navList` 데이터를 함께 관리하도록 수정하여, `navList`의 변경에 따라 미리보기 페이지의 컴포넌트도 동적으로 변경됩니다.
=> 📝 PR: Nav 드래그앤 드롭으로 미리보기 페이지 순서 변경 #134

src/api/GithubApi.jsx, src/components/templates/Profile/ProfilePreview.jsx
깃허브 토큰이용한 데이터 수집 => 깃허브 아이디로 커밋 이미지 가져오기 변경
- 기존 깃허브 토큰으로 데이터 수집하는 함수 주석처리 후 깃허브 아이디 인풋 및 저장 기능 추가
- 내 잔디 불러오기 버튼 클릭시 resumeData에 github: [깃허브 아이디, 커밋 이미지 src] 형식으로 저장
- 임시 저장 버튼 클릭시 로컬 스토리지에 저장
- 작성 페이지, 미리보기 페이지에서 받아온 데이터 렌더링
close: #124
=> ✨ Fix: github아이디 인풋 및 기능 변경

src/App.jsx, src/components/atoms/Button/MainBtn.jsx, src/components/atoms/Button/ToggleBtn.jsx, src/components/atoms/ColorIcon/ColorIcon.jsx, src/components/atoms/Nav/NavList.jsx, src/components/organisms/ColorPicker/ColorPicker.jsx, src/components/organisms/Nav/PreviewBox.jsx, src/context/PageContext.jsx
작성 페이지 / 미리보기 페이지 메인컬러 적용 파트 구분
- 작성 페이지: 기존 위니브 메인컬러 유지
- 미리보기 페이지: 토글 버튼, 로고, 메인 버튼 + pdf 출력 파트 전체적으로 mainColor 동적 적용
=> ✨ Feat: 메인컬러 적용 파트 구분

src/components/templates/Career/CareerPreview.jsx, src/components/templates/Certificate/CertificatePreview.jsx, src/components/templates/Education/EducationPreview.jsx, src/components/templates/Experience/ExperiencePreview.jsx, src/components/templates/Intro/IntroPreview.jsx, src/components/templates/Profile/ProfilePreview.jsx, src/components/templates/Project/ProjectPreview.jsx, src/components/templates/Url/UrlPreview.jsx, src/pages/PreviewPage.jsx
- PDF 내보내기(출력) 페이지 분할 기준 수정
- Career, Project의 경우 항목 요소에 `break-inside:avoid;` 속성을 주어 해당 요소가 분할되지 않도록 수정
- 첫번째 항목 요소에 break-before:avoid도 함께 주어, 첫번째 항목 요소와 제목 요소가 함께 움직이도록 설정
- 나머지 항목은 섹션 전체에 `break-inside:avoid;`를 주어 섹션 단위로 이동할 수 있게 설정
- mdn 문서에는 page-break-~ 속성이 break-~로 변경되었다고 명시되어 있음.
- 호환성 유지를 위하여 두 속성값을 모두 갖도록 설정
=> 📝 PR: PDF 내보내기 페이지 분할 기준 수정

src/components/templates/Project/ProjectPreview.jsx
- 기존 `--background-color` 변수 사용 시, 다크모드에서 보이지 않는 이슈 발생
- 다크모드 여부에 관계 없이 `#ffffff` 값으로 고정
close #155
=> 💄 Style: 프로젝트 적용 기술 텍스트 색상 고정

src/components/atoms/Input/DefaultTextarea.jsx, src/components/organisms/Component/Project.jsx, src/components/templates/Intro/Intro.jsx, src/components/templates/Project/ProjectPreview.jsx
- Project 미리보기 컴포넌트의 세부 타이틀을 삭제
- 인원 항목의 폰트크기를 다른 항목들과 통일
- 아래와 같이 변경되었습니다.
=> 📝 PR: Project 미리보기 세부 타이틀 삭제 #164

src/components/atoms/Input/DefaultTextarea.jsx
(경림님 피드백) DefaultTextarea 컴포넌트 내 스크롤 추가 +윈도우 대응을 위한 커스터마이징
close #176
=> 💄 Style: DefaultTextarea 커스텀 스크롤 추가

src/components/atoms/SkillList/SkillList.jsx, src/components/templates/Intro/IntroPreview.jsx
구버전 디자인에 맞춰 Skills 미리보기 섹션 구현
- 자기소개서 하단 배치
- Skills 타이틀 옆 아이템 일렬 배치 
- mainColor 동적 적용을 위한 `SkillList` 컴포넌트 내 `type='preview'` 추가 
close #180
=> 💄 UI: Skills 미리보기 섹션 구현

src/App.jsx, src/components/atoms/Button/MainBtn.jsx, src/pages/QuitPage.jsx, src/pages/index.js
탈퇴 완료 페이지 UI 구현
- `width: 100%`인 MainBtn 사용 시 `type='full'` 지정 필요 (같은 '메인으로' 버튼이어도 너비가 다른 경우가 있음)
- 메인 페이지로 이동하는 함수는 편의상 추후 따로 분리하면 좋을 것 같습니다.
close #193
=> 💄 Style: 탈퇴 완료 페이지 UI 구현

src/components/atoms/PreviewItem/PreviewMonthItem.jsx, src/components/templates/Career/CareerPreview.jsx, src/components/templates/Certificate/CertificatePreview.jsx, src/components/templates/Education/EducationPreview.jsx, src/components/templates/Experience/ExperiencePreview.jsx, src/components/templates/Project/ProjectPreview.jsx, src/pages/PreviewPage.jsx
- 항목이 없는 경우 출력되지 않도록 수정
- 진행 중인 경우 '진행 중' 또는 '재직 중'으로 출력되도록 수정
- <Component>의 반환값이 없더라도 div로 인해 영역이 생겨, 바로 <Component/>를 출력하도록 수정
- 불필요한 요소 삭제를 통한 시맨틱 마크업
```jsx
return (
<div key={index}> {/* div 제거 */}
<Component />
</div>
)
```
close #152 
1. isInvalid 
-  값이 하나라도 있으면 날짜 또는 진행 여부를 표시하도록 수정
```js
const isInvalid = !(exp.startDate || exp.endDate || exp.inProgress)
```
2. 출력 스타일 논의 필요 `10/25 회의에서 진행`
#159
=> 📝 PR: 미리보기 페이지 항목 출력 유효성

src/components/atoms/Nav/NavList.jsx, src/components/organisms/Nav/NavBar.jsx
- navBar 미리보기 페이지 드래그앤 드롭 버튼 제거
- 미리보기 항목 새로고침 시 유지
- navBar 미리보기 페이지 드래그앤 드롭 버튼 제거
기존에 없던 기능인데, 체크박스 삭제하면서 미리보기 페이지에도 렌더링 되고 있어 기존 대로 type에 따라 조건부 렌더링 되도록 변경해두었습니다.
- 미리보기 항목 새로고침 시 유지
간단한 기능이라 해당 코드 변경하면서 같이 변경했습니다. 현재는 resumeOrder라는 이름으로 이력서 하나의 항목만 관리되고 있고, 추후 api연동으로 여러 이력서 관리될 경우 이력서 고유 id값이나 인덱스값으로 이력서 구분해서 저장하도록 변경하겠습니다.
=> 🔥 Remove: 미리보기 페이지 드래그앤드롭 기능 제거

src/components/templates/Intro/IntroPreview.jsx, src/components/templates/Profile/ProfilePreview.jsx
- 스타일링 시 변수를 지정하지 않아 다크모드로 pdf 출력 시 변경된 색상 값이 적용되지 않는 이슈
- 변수 지정 필요 (ex. `color: var(--surface-color)` )
=> 💄 Style: 프로필, 자기소개 글자 색상 값 지정

src/components/organisms/Component/Career.jsx, src/components/organisms/Component/Certificate.jsx, src/components/organisms/Component/Education.jsx, src/components/organisms/Component/Experience.jsx, src/components/organisms/Component/Project.jsx, src/components/organisms/Component/Url.jsx, src/components/organisms/ComponentHeader/ComponentHeader.jsx, src/components/templates/Career/Career.jsx, src/components/templates/Certificate/Certificate.jsx, src/components/templates/Education/Education.jsx, src/components/templates/Experience/Experience.jsx, src/components/templates/Project/Project.jsx, src/components/templates/Url/Url.jsx
- 커리어, 프로젝트, 경험, 자격증, 교육, 추가URL 컴포넌트 아코디언 메뉴가 제대로 펼쳐지지않는 오류 존재
- 한번에 하나의 아코디언 메뉴만 오픈되도록 수정
- 초기에는 0번 메뉴가 열려있도록 수정
- `ComponentHeader` 컴포넌트 props 추가
-  isOpen
- onAccordionClick
=> 📝 PR: 아코디언 메뉴 컴포넌트 동작 버그 수정

src/components/templates/Project/ProjectPreview.jsx
-다크모드 적용 후 PDF 출력시 미리보기창에서 프로젝트 설명 파트가 다크모드가 적용되지않는 문제가 있었음
- 미리보기시에는 문제가 발생하지않
- `ProjectPreview.jsx` 컴포넌트 outline 클래스에 color 속성 추가
- [] Moblie
- [] Mac
=> 📝 PR: 프로젝트 설명 파트 PDF 출력시 다크 모드 적용안되는 문제 해결 #231

src/App.jsx, src/components/atoms/Auth/Layout.jsx, src/pages/LoginPage.jsx, src/pages/SignupPage.jsx
- 소셜 로그인 기능이 삭제됨에따라 로그인 페이지에서 소셜 로그인 버튼 삭제
- `src\components\atoms\Auth\Layout.jsx` props로 auth 추가 (로그인, 회원가입 페이지에서 사용)
- auth=true의 경우, section에 적용된 align-item을 center에서 start로 변경
- auth=true의 경우, margin-top: 60px 추가
- 회원가입 완료시 기본 프로필 설정 페이지로 이동하도록 수정 (기존에는 회원가입 완료 페이지 출력)
=> 📝 PR: 소셜 로그인기능 삭제 및 로그인/회원가입 페이지 UI 수정

src/components/templates/Profile/ProfilePreview.jsx
=> :bug: Edit: 잔디가 없을 때 로딩 인디케이터 보이는 현상 해결

src/components/organisms/Nav/PreviewBox.jsx, src/pages/PreviewPage.jsx, src/styles/GlobalStyles.jsx
- PDF 내보내기 여백 설정
- 출력 라이트 모드 지정
- @page 스타일링을 통해 인쇄 옵션을 설정
```css
@page {
size: 210mm 297mm;
margin: 20mm;
}
```
- 다크모드에서 여백은 배경색상이 지정되지 않음. 
- 미디어 쿼리를 이용하여 print인 경우에 라이트 모드 변수를 사용 `✅ 현재 적용된 방식`
```css
@media print {
:root {
--primary-color:  ${lightTheme.primaryColor};
--secondary-color: ${lightTheme.secondaryColor};
(생략)
```
- 사용자 입력에 따라 페이지 분할 위치가 다름
- 페이지에 옵션을 제거하고, 출력할 컴포넌트에 padding을 조절하면 분할 위치마다 여백이 적용되지 않음
close #260
=> 📝 PR: 출력 여백 설정 및 라이트모드 지정

src/components/atoms/SkillList/SkillList.jsx, src/components/templates/Intro/IntroPreview.jsx
아래 이슈에서 언급되었던 '경험' 관련 항목은 추가 필드 관련 사항이므로 #259 이슈에서 별도 처리되고 있습니다.
close #266
=> 💄 Style: 미리보기 skills 리스트 스타일 수정

src/pages/LandingPage.jsx
작성 가능한 이력서 개수 변경으로 인해 랜딩 페이지 내 '이력서 만들기' 관련 버튼 클릭 시 이동하는 URL 변경 (`/write` -> `/myresume`)
=> ✨ Feat: 랜딩페이지 버튼 이동 링크 변경 (write → 마이페이지)

src/components/organisms/Component/Resume.jsx, src/components/templates/Career/Career.jsx, src/components/templates/Profile/Profile.jsx
- 더보기 버튼 내부에 있던 이력서 수정 및 삭제 버튼을 외부로 이동
- 이력서 이름 클릭시 이력서 수정 페이지로 이동
- 이력서 이름 hover 시 text-decoration: underline 추가
- 더보기 버튼을 삭제버튼으로 수정 후 이력서 삭제 기능을 수행하도록 변경
=> 📝 PR: 마이페이지 이력서 수정 및 삭제 버튼 수정

src/components/templates/Profile/DefaultProfile.jsx, src/components/templates/Profile/Profile-style.jsx, src/pages/MyProfilePage.jsx
- 기본 프로필을 처음 저장하는 경우가 있을 수 있으므로 텍스트 수정 (수정하기 → 저장하기)
- 사용자 편의를 위해 form 우측 상단에 버튼 추가 
close #293
=> 💄 Style: 기본 프로필 저장 버튼 추가 및 수정

src/components/organisms/Component/Resume.jsx
- 이력서 상세 보기 이동 범위 수정
- 마우스 호버 시 아웃라인 효과 추가
- 수정, 삭제 메뉴를 케밥 메뉴로 통일
- 전체 블록을 이동 범위로 수정
- 제목 수정 중이 아닌 경우에만 마우스 호버 아웃라인 효과 및 이동 처리
=> 📝 PR: 이력서 상세보기 이동 범위 수정

src/components/templates/Profile/DefaultProfile.jsx, src/components/templates/Profile/Profile-style.jsx, src/context/ProfileContext.jsx, src/pages/MyProfilePage.jsx
하단 저장 버튼 클릭 시 새로 입력한 데이터 값이 저장되지 않고 기존 로컬스토리지 데이터로 초기화되는 현상 수정
`DefaultProfile` 컴포넌트 내부 버튼으로 이동 및 상단 저장 버튼의 데이터 및 함수 공유
close #302
=> 🐛 Fix: 기본 프로필 하단 저장 버튼 에러 수정

src/components/templates/Project/ProjectPreview.jsx, src/data/dummy.js
- `ProjectPreview.jsx` > `InformationBox` 내부 요소 없는 경우 UI 출력 안되도록 처리
- contributions(기여 부분)의 경우 무조건 첫 값이 빈 문자열로 존재해야 작성 시 기본 input이 주어지므로 개발 인원, 적용 기술 파트와 다르게 처리 
- 첫 요소가 빈 문자열이 아닌지 확인
close #315
=> ✨ Feat: 프로젝트 미리보기 시 컨텐츠 없는 경우 예외 처리 추가

src/components/templates/Profile/ProfilePreview.jsx
- 깃허브 입력 여부를 commitURL이 아닌 githubID로 확인 
- commitURL: 아이디를 입력하지 않았을 시에 계정명 undefined로 항시 존재
- githubID: 아이디 입력 시 이력서 내 프로필 항목으로 저장 
- 기존 로딩 스피너는 메인 컬러 변경 시 commitURL 유무로 등장했는데, 아이디가 없을 시에도 commitURL은 존재하기에 따로 동작하지 않아 임시 주석처리해두었습니다. 
close #318
=> ✨ Feat: 깃허브 아이디 입력하지 않았을 때 빈 잔디 UI 제거

src/components/atoms/Input/DefaultInput.jsx, src/components/atoms/Input/RequireInput.jsx, src/components/organisms/Component/Certificate.jsx, src/components/organisms/Component/Education.jsx, src/components/organisms/Component/Experience.jsx, src/components/organisms/Component/Url.jsx
- `DefaultInput` 컴포넌트의 `autofocus` 속성으로 인해 각 페이지의 마지막 `DefaultInput`에 포커싱되는 이슈 발생
- 사용자 편의를 위해 첫 번째 input에 자동 포커싱될 필요가 있어 아래와 같이 수정했습니다.
- 수정 대상 컴포넌트: `DefaultInput`, `RequireInput`
- 공통적으로 `useRef`를 사용하나, 추가적인 `props` 전달에 차이가 있습니다
- `DefaultInput`: 사용되는 곳이 많으므로 첫 번째 요소 여부 확인을 위한 `isFirst props` 전달
- `RequireInput` (이름, 회사명, 프로젝트명): 항시 각 섹션의 첫 번째 항목이므로 useRef만 사용
close #319
=> 🐛 Fix: 랜덤 포커싱 이슈 수정 (첫 번째 input에 자동 포커싱 되도록)

src/components/atoms/Github/GetCommitRecord.jsx, src/components/templates/Project/Project.jsx
=> 📝 PR: GitHub 아이디 변경 방식 변경 #320
